#pragma warning(disable : 4786)
//#include "../Common/Controls/xShadeButton.h"
//#include "../Common/Controls/CxStatic.h"
//#include "../Common/Controls/label.h"
//#include "../Common/Controls/XTipComboBox.h"
//#include "../Common/Controls/TransparentStatic2.h"
//#include "../Common/Controls/StaticTrans.h"
#include "../Common/Controls/XPGroupBox.h"
//#include "../Common/Controls/XListCtrl.h"
//#include "../Common/Controls/NumSpinCtrl.h"
//#include "../Common/Controls/ReadOnlyComboHandler.h"
//#include "../Common/Controls/led.h"
//#include "../Common/Controls/FileDialog_ReadOnly.h"
//#include "../Common/Controls/ProgressCtrlX.h"
//#include "../Common/Controls/FilenameEdit.h"
//#include "../Common/Controls/GridCtrl/GridCtrl.h"
//#include "../Common/Controls/amsEdit.h"
//#include "../Common/Controls/PPTooltip.h"
//#include "../Common/Controls/NewCellTypes/GridCellNumeric.h"
#include "../Common/Controls/GroupCheck.h"
//#include "../Common/Controls/easysize.h"
#pragma comment(lib, "Controls.lib")
