// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "comigraph.h"

// Dispatch interfaces referenced by this interface
#include "font.h"

/////////////////////////////////////////////////////////////////////////////
// CComiGraph

IMPLEMENT_DYNCREATE(CComiGraph, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CComiGraph properties

unsigned long CComiGraph::GetPlotBackColor()
{
	unsigned long result;
	GetProperty(0x1, VT_I4, (void*)&result);
	return result;
}

void CComiGraph::SetPlotBackColor(unsigned long propVal)
{
	SetProperty(0x1, VT_I4, propVal);
}

COleFont CComiGraph::GetAxisTitleFont()
{
	LPDISPATCH pDispatch;
	GetProperty(0x2, VT_DISPATCH, (void*)&pDispatch);
	return COleFont(pDispatch);
}

void CComiGraph::SetAxisTitleFont(LPDISPATCH propVal)
{
	SetProperty(0x2, VT_DISPATCH, propVal);
}

short CComiGraph::GetFrameStyle()
{
	short result;
	GetProperty(0x3, VT_I2, (void*)&result);
	return result;
}

void CComiGraph::SetFrameStyle(short propVal)
{
	SetProperty(0x3, VT_I2, propVal);
}

long CComiGraph::GetStandardFrameID()
{
	long result;
	GetProperty(0x4, VT_I4, (void*)&result);
	return result;
}

void CComiGraph::SetStandardFrameID(long propVal)
{
	SetProperty(0x4, VT_I4, propVal);
}

unsigned long CComiGraph::GetGraphFrameColor()
{
	unsigned long result;
	GetProperty(0x5, VT_I4, (void*)&result);
	return result;
}

void CComiGraph::SetGraphFrameColor(unsigned long propVal)
{
	SetProperty(0x5, VT_I4, propVal);
}

unsigned long CComiGraph::GetMajorGridColor()
{
	unsigned long result;
	GetProperty(0x6, VT_I4, (void*)&result);
	return result;
}

void CComiGraph::SetMajorGridColor(unsigned long propVal)
{
	SetProperty(0x6, VT_I4, propVal);
}

unsigned long CComiGraph::GetMinorGridColor()
{
	unsigned long result;
	GetProperty(0x7, VT_I4, (void*)&result);
	return result;
}

void CComiGraph::SetMinorGridColor(unsigned long propVal)
{
	SetProperty(0x7, VT_I4, propVal);
}

unsigned long CComiGraph::GetGraphTitleColor()
{
	unsigned long result;
	GetProperty(0x8, VT_I4, (void*)&result);
	return result;
}

void CComiGraph::SetGraphTitleColor(unsigned long propVal)
{
	SetProperty(0x8, VT_I4, propVal);
}

COleFont CComiGraph::GetGraphTitleFont()
{
	LPDISPATCH pDispatch;
	GetProperty(0x9, VT_DISPATCH, (void*)&pDispatch);
	return COleFont(pDispatch);
}

void CComiGraph::SetGraphTitleFont(LPDISPATCH propVal)
{
	SetProperty(0x9, VT_DISPATCH, propVal);
}

COleFont CComiGraph::GetTickLabelFont()
{
	LPDISPATCH pDispatch;
	GetProperty(0xa, VT_DISPATCH, (void*)&pDispatch);
	return COleFont(pDispatch);
}

void CComiGraph::SetTickLabelFont(LPDISPATCH propVal)
{
	SetProperty(0xa, VT_DISPATCH, propVal);
}

COleFont CComiGraph::GetCursorValueFont()
{
	LPDISPATCH pDispatch;
	GetProperty(0xb, VT_DISPATCH, (void*)&pDispatch);
	return COleFont(pDispatch);
}

void CComiGraph::SetCursorValueFont(LPDISPATCH propVal)
{
	SetProperty(0xb, VT_DISPATCH, propVal);
}

COleFont CComiGraph::GetLegendTextFont()
{
	LPDISPATCH pDispatch;
	GetProperty(0xc, VT_DISPATCH, (void*)&pDispatch);
	return COleFont(pDispatch);
}

void CComiGraph::SetLegendTextFont(LPDISPATCH propVal)
{
	SetProperty(0xc, VT_DISPATCH, propVal);
}

BOOL CComiGraph::GetGraphTitleVisible()
{
	BOOL result;
	GetProperty(0xd, VT_BOOL, (void*)&result);
	return result;
}

void CComiGraph::SetGraphTitleVisible(BOOL propVal)
{
	SetProperty(0xd, VT_BOOL, propVal);
}

CString CComiGraph::GetGraphTitle()
{
	CString result;
	GetProperty(0xe, VT_BSTR, (void*)&result);
	return result;
}

void CComiGraph::SetGraphTitle(LPCTSTR propVal)
{
	SetProperty(0xe, VT_BSTR, propVal);
}

short CComiGraph::GetGraphTitlePosition()
{
	short result;
	GetProperty(0xf, VT_I2, (void*)&result);
	return result;
}

void CComiGraph::SetGraphTitlePosition(short propVal)
{
	SetProperty(0xf, VT_I2, propVal);
}

long CComiGraph::GetFrameOffsetLeft()
{
	long result;
	GetProperty(0x10, VT_I4, (void*)&result);
	return result;
}

void CComiGraph::SetFrameOffsetLeft(long propVal)
{
	SetProperty(0x10, VT_I4, propVal);
}

long CComiGraph::GetFrameOffsetTop()
{
	long result;
	GetProperty(0x11, VT_I4, (void*)&result);
	return result;
}

void CComiGraph::SetFrameOffsetTop(long propVal)
{
	SetProperty(0x11, VT_I4, propVal);
}

long CComiGraph::GetFrameOffsetRight()
{
	long result;
	GetProperty(0x12, VT_I4, (void*)&result);
	return result;
}

void CComiGraph::SetFrameOffsetRight(long propVal)
{
	SetProperty(0x12, VT_I4, propVal);
}

long CComiGraph::GetFrameOffsetBottom()
{
	long result;
	GetProperty(0x13, VT_I4, (void*)&result);
	return result;
}

void CComiGraph::SetFrameOffsetBottom(long propVal)
{
	SetProperty(0x13, VT_I4, propVal);
}

short CComiGraph::GetNumDivisionMajorX()
{
	short result;
	GetProperty(0x14, VT_I2, (void*)&result);
	return result;
}

void CComiGraph::SetNumDivisionMajorX(short propVal)
{
	SetProperty(0x14, VT_I2, propVal);
}

short CComiGraph::GetNumDivisionMajorY()
{
	short result;
	GetProperty(0x15, VT_I2, (void*)&result);
	return result;
}

void CComiGraph::SetNumDivisionMajorY(short propVal)
{
	SetProperty(0x15, VT_I2, propVal);
}

short CComiGraph::GetNumDivisionMinorX()
{
	short result;
	GetProperty(0x16, VT_I2, (void*)&result);
	return result;
}

void CComiGraph::SetNumDivisionMinorX(short propVal)
{
	SetProperty(0x16, VT_I2, propVal);
}

short CComiGraph::GetNumDivisionMinorY()
{
	short result;
	GetProperty(0x17, VT_I2, (void*)&result);
	return result;
}

void CComiGraph::SetNumDivisionMinorY(short propVal)
{
	SetProperty(0x17, VT_I2, propVal);
}

long CComiGraph::GetMajorGridLineStyle()
{
	long result;
	GetProperty(0x18, VT_I4, (void*)&result);
	return result;
}

void CComiGraph::SetMajorGridLineStyle(long propVal)
{
	SetProperty(0x18, VT_I4, propVal);
}

long CComiGraph::GetMinorGridLineStyle()
{
	long result;
	GetProperty(0x19, VT_I4, (void*)&result);
	return result;
}

void CComiGraph::SetMinorGridLineStyle(long propVal)
{
	SetProperty(0x19, VT_I4, propVal);
}

long CComiGraph::GetMajorTickLength()
{
	long result;
	GetProperty(0x1a, VT_I4, (void*)&result);
	return result;
}

void CComiGraph::SetMajorTickLength(long propVal)
{
	SetProperty(0x1a, VT_I4, propVal);
}

long CComiGraph::GetMajorTickWidth()
{
	long result;
	GetProperty(0x1b, VT_I4, (void*)&result);
	return result;
}

void CComiGraph::SetMajorTickWidth(long propVal)
{
	SetProperty(0x1b, VT_I4, propVal);
}

long CComiGraph::GetMinorTickLength()
{
	long result;
	GetProperty(0x1c, VT_I4, (void*)&result);
	return result;
}

void CComiGraph::SetMinorTickLength(long propVal)
{
	SetProperty(0x1c, VT_I4, propVal);
}

long CComiGraph::GetMinorTickWidth()
{
	long result;
	GetProperty(0x1d, VT_I4, (void*)&result);
	return result;
}

void CComiGraph::SetMinorTickWidth(long propVal)
{
	SetProperty(0x1d, VT_I4, propVal);
}

BOOL CComiGraph::GetMajorGridXVisible()
{
	BOOL result;
	GetProperty(0x1e, VT_BOOL, (void*)&result);
	return result;
}

void CComiGraph::SetMajorGridXVisible(BOOL propVal)
{
	SetProperty(0x1e, VT_BOOL, propVal);
}

BOOL CComiGraph::GetMinorGridXVisible()
{
	BOOL result;
	GetProperty(0x1f, VT_BOOL, (void*)&result);
	return result;
}

void CComiGraph::SetMinorGridXVisible(BOOL propVal)
{
	SetProperty(0x1f, VT_BOOL, propVal);
}

BOOL CComiGraph::GetMajorTickVisible()
{
	BOOL result;
	GetProperty(0x20, VT_BOOL, (void*)&result);
	return result;
}

void CComiGraph::SetMajorTickVisible(BOOL propVal)
{
	SetProperty(0x20, VT_BOOL, propVal);
}

BOOL CComiGraph::GetMinorTickVisible()
{
	BOOL result;
	GetProperty(0x21, VT_BOOL, (void*)&result);
	return result;
}

void CComiGraph::SetMinorTickVisible(BOOL propVal)
{
	SetProperty(0x21, VT_BOOL, propVal);
}

long CComiGraph::GetTargetXAxis()
{
	long result;
	GetProperty(0x22, VT_I4, (void*)&result);
	return result;
}

void CComiGraph::SetTargetXAxis(long propVal)
{
	SetProperty(0x22, VT_I4, propVal);
}

CString CComiGraph::GetXAxisTitle()
{
	CString result;
	GetProperty(0x23, VT_BSTR, (void*)&result);
	return result;
}

void CComiGraph::SetXAxisTitle(LPCTSTR propVal)
{
	SetProperty(0x23, VT_BSTR, propVal);
}

short CComiGraph::GetXAxisPosition()
{
	short result;
	GetProperty(0x24, VT_I2, (void*)&result);
	return result;
}

void CComiGraph::SetXAxisPosition(short propVal)
{
	SetProperty(0x24, VT_I2, propVal);
}

short CComiGraph::GetXAxisScaleMode()
{
	short result;
	GetProperty(0x25, VT_I2, (void*)&result);
	return result;
}

void CComiGraph::SetXAxisScaleMode(short propVal)
{
	SetProperty(0x25, VT_I2, propVal);
}

unsigned long CComiGraph::GetXAxisScaleColor()
{
	unsigned long result;
	GetProperty(0x26, VT_I4, (void*)&result);
	return result;
}

void CComiGraph::SetXAxisScaleColor(unsigned long propVal)
{
	SetProperty(0x26, VT_I4, propVal);
}

unsigned long CComiGraph::GetXAxisTitleColor()
{
	unsigned long result;
	GetProperty(0x27, VT_I4, (void*)&result);
	return result;
}

void CComiGraph::SetXAxisTitleColor(unsigned long propVal)
{
	SetProperty(0x27, VT_I4, propVal);
}

unsigned long CComiGraph::GetXAxisTickLabelColor()
{
	unsigned long result;
	GetProperty(0x28, VT_I4, (void*)&result);
	return result;
}

void CComiGraph::SetXAxisTickLabelColor(unsigned long propVal)
{
	SetProperty(0x28, VT_I4, propVal);
}

double CComiGraph::GetXAxisRangeMin()
{
	double result;
	GetProperty(0x29, VT_R8, (void*)&result);
	return result;
}

void CComiGraph::SetXAxisRangeMin(double propVal)
{
	SetProperty(0x29, VT_R8, propVal);
}

double CComiGraph::GetXAxisRangeMax()
{
	double result;
	GetProperty(0x2a, VT_R8, (void*)&result);
	return result;
}

void CComiGraph::SetXAxisRangeMax(double propVal)
{
	SetProperty(0x2a, VT_R8, propVal);
}

BOOL CComiGraph::GetXAxisVisible()
{
	BOOL result;
	GetProperty(0x2b, VT_BOOL, (void*)&result);
	return result;
}

void CComiGraph::SetXAxisVisible(BOOL propVal)
{
	SetProperty(0x2b, VT_BOOL, propVal);
}

BOOL CComiGraph::GetXAxisTitleVisible()
{
	BOOL result;
	GetProperty(0x2c, VT_BOOL, (void*)&result);
	return result;
}

void CComiGraph::SetXAxisTitleVisible(BOOL propVal)
{
	SetProperty(0x2c, VT_BOOL, propVal);
}

BOOL CComiGraph::GetXAxisTickLabelVisible()
{
	BOOL result;
	GetProperty(0x2d, VT_BOOL, (void*)&result);
	return result;
}

void CComiGraph::SetXAxisTickLabelVisible(BOOL propVal)
{
	SetProperty(0x2d, VT_BOOL, propVal);
}

BOOL CComiGraph::GetMajorGridYVisible()
{
	BOOL result;
	GetProperty(0x2e, VT_BOOL, (void*)&result);
	return result;
}

void CComiGraph::SetMajorGridYVisible(BOOL propVal)
{
	SetProperty(0x2e, VT_BOOL, propVal);
}

BOOL CComiGraph::GetMinorGridYVisible()
{
	BOOL result;
	GetProperty(0x2f, VT_BOOL, (void*)&result);
	return result;
}

void CComiGraph::SetMinorGridYVisible(BOOL propVal)
{
	SetProperty(0x2f, VT_BOOL, propVal);
}

BOOL CComiGraph::GetXAxisMinorTickVisible()
{
	BOOL result;
	GetProperty(0x30, VT_BOOL, (void*)&result);
	return result;
}

void CComiGraph::SetXAxisMinorTickVisible(BOOL propVal)
{
	SetProperty(0x30, VT_BOOL, propVal);
}

long CComiGraph::GetTargetYAxis()
{
	long result;
	GetProperty(0x31, VT_I4, (void*)&result);
	return result;
}

void CComiGraph::SetTargetYAxis(long propVal)
{
	SetProperty(0x31, VT_I4, propVal);
}

CString CComiGraph::GetYAxisTitle()
{
	CString result;
	GetProperty(0x32, VT_BSTR, (void*)&result);
	return result;
}

void CComiGraph::SetYAxisTitle(LPCTSTR propVal)
{
	SetProperty(0x32, VT_BSTR, propVal);
}

short CComiGraph::GetYAxisPosition()
{
	short result;
	GetProperty(0x33, VT_I2, (void*)&result);
	return result;
}

void CComiGraph::SetYAxisPosition(short propVal)
{
	SetProperty(0x33, VT_I2, propVal);
}

short CComiGraph::GetYAxisScaleMode()
{
	short result;
	GetProperty(0x34, VT_I2, (void*)&result);
	return result;
}

void CComiGraph::SetYAxisScaleMode(short propVal)
{
	SetProperty(0x34, VT_I2, propVal);
}

unsigned long CComiGraph::GetYAxisScaleColor()
{
	unsigned long result;
	GetProperty(0x35, VT_I4, (void*)&result);
	return result;
}

void CComiGraph::SetYAxisScaleColor(unsigned long propVal)
{
	SetProperty(0x35, VT_I4, propVal);
}

unsigned long CComiGraph::GetYAxisTitleColor()
{
	unsigned long result;
	GetProperty(0x36, VT_I4, (void*)&result);
	return result;
}

void CComiGraph::SetYAxisTitleColor(unsigned long propVal)
{
	SetProperty(0x36, VT_I4, propVal);
}

unsigned long CComiGraph::GetYAxisTickLabelColor()
{
	unsigned long result;
	GetProperty(0x37, VT_I4, (void*)&result);
	return result;
}

void CComiGraph::SetYAxisTickLabelColor(unsigned long propVal)
{
	SetProperty(0x37, VT_I4, propVal);
}

double CComiGraph::GetYAxisRangeMin()
{
	double result;
	GetProperty(0x38, VT_R8, (void*)&result);
	return result;
}

void CComiGraph::SetYAxisRangeMin(double propVal)
{
	SetProperty(0x38, VT_R8, propVal);
}

double CComiGraph::GetYAxisRangeMax()
{
	double result;
	GetProperty(0x39, VT_R8, (void*)&result);
	return result;
}

void CComiGraph::SetYAxisRangeMax(double propVal)
{
	SetProperty(0x39, VT_R8, propVal);
}

long CComiGraph::GetYAxisSpaceOffset()
{
	long result;
	GetProperty(0x3a, VT_I4, (void*)&result);
	return result;
}

void CComiGraph::SetYAxisSpaceOffset(long propVal)
{
	SetProperty(0x3a, VT_I4, propVal);
}

BOOL CComiGraph::GetYAxisVisible()
{
	BOOL result;
	GetProperty(0x3b, VT_BOOL, (void*)&result);
	return result;
}

void CComiGraph::SetYAxisVisible(BOOL propVal)
{
	SetProperty(0x3b, VT_BOOL, propVal);
}

BOOL CComiGraph::GetYAxisTitleVisible()
{
	BOOL result;
	GetProperty(0x3c, VT_BOOL, (void*)&result);
	return result;
}

void CComiGraph::SetYAxisTitleVisible(BOOL propVal)
{
	SetProperty(0x3c, VT_BOOL, propVal);
}

BOOL CComiGraph::GetYAxisTickLabelVisible()
{
	BOOL result;
	GetProperty(0x3d, VT_BOOL, (void*)&result);
	return result;
}

void CComiGraph::SetYAxisTickLabelVisible(BOOL propVal)
{
	SetProperty(0x3d, VT_BOOL, propVal);
}

BOOL CComiGraph::GetYAxisMinorTickVisible()
{
	BOOL result;
	GetProperty(0x3e, VT_BOOL, (void*)&result);
	return result;
}

void CComiGraph::SetYAxisMinorTickVisible(BOOL propVal)
{
	SetProperty(0x3e, VT_BOOL, propVal);
}

long CComiGraph::GetXAxisSpaceOffset()
{
	long result;
	GetProperty(0x3f, VT_I4, (void*)&result);
	return result;
}

void CComiGraph::SetXAxisSpaceOffset(long propVal)
{
	SetProperty(0x3f, VT_I4, propVal);
}

long CComiGraph::GetTargetChannel()
{
	long result;
	GetProperty(0x40, VT_I4, (void*)&result);
	return result;
}

void CComiGraph::SetTargetChannel(long propVal)
{
	SetProperty(0x40, VT_I4, propVal);
}

BOOL CComiGraph::GetChannelVisible()
{
	BOOL result;
	GetProperty(0x41, VT_BOOL, (void*)&result);
	return result;
}

void CComiGraph::SetChannelVisible(BOOL propVal)
{
	SetProperty(0x41, VT_BOOL, propVal);
}

CString CComiGraph::GetChannelTitle()
{
	CString result;
	GetProperty(0x42, VT_BSTR, (void*)&result);
	return result;
}

void CComiGraph::SetChannelTitle(LPCTSTR propVal)
{
	SetProperty(0x42, VT_BSTR, propVal);
}

unsigned long CComiGraph::GetChannelColor()
{
	unsigned long result;
	GetProperty(0x43, VT_I4, (void*)&result);
	return result;
}

void CComiGraph::SetChannelColor(unsigned long propVal)
{
	SetProperty(0x43, VT_I4, propVal);
}

short CComiGraph::GetChannelXAxis()
{
	short result;
	GetProperty(0x44, VT_I2, (void*)&result);
	return result;
}

void CComiGraph::SetChannelXAxis(short propVal)
{
	SetProperty(0x44, VT_I2, propVal);
}

short CComiGraph::GetChannelYAxis()
{
	short result;
	GetProperty(0x45, VT_I2, (void*)&result);
	return result;
}

void CComiGraph::SetChannelYAxis(short propVal)
{
	SetProperty(0x45, VT_I2, propVal);
}

long CComiGraph::GetChannelPlotStyle()
{
	long result;
	GetProperty(0x46, VT_I4, (void*)&result);
	return result;
}

void CComiGraph::SetChannelPlotStyle(long propVal)
{
	SetProperty(0x46, VT_I4, propVal);
}

long CComiGraph::GetChannelLineStyle()
{
	long result;
	GetProperty(0x47, VT_I4, (void*)&result);
	return result;
}

void CComiGraph::SetChannelLineStyle(long propVal)
{
	SetProperty(0x47, VT_I4, propVal);
}

long CComiGraph::GetChannelLineWidth()
{
	long result;
	GetProperty(0x48, VT_I4, (void*)&result);
	return result;
}

void CComiGraph::SetChannelLineWidth(long propVal)
{
	SetProperty(0x48, VT_I4, propVal);
}

long CComiGraph::GetChannelMarkerStyle()
{
	long result;
	GetProperty(0x49, VT_I4, (void*)&result);
	return result;
}

void CComiGraph::SetChannelMarkerStyle(long propVal)
{
	SetProperty(0x49, VT_I4, propVal);
}

long CComiGraph::GetChannelMarkerSize()
{
	long result;
	GetProperty(0x4a, VT_I4, (void*)&result);
	return result;
}

void CComiGraph::SetChannelMarkerSize(long propVal)
{
	SetProperty(0x4a, VT_I4, propVal);
}

unsigned long CComiGraph::GetChannelMarkerColor()
{
	unsigned long result;
	GetProperty(0x4b, VT_I4, (void*)&result);
	return result;
}

void CComiGraph::SetChannelMarkerColor(unsigned long propVal)
{
	SetProperty(0x4b, VT_I4, propVal);
}

BOOL CComiGraph::GetChannelMarkerFill()
{
	BOOL result;
	GetProperty(0x4c, VT_BOOL, (void*)&result);
	return result;
}

void CComiGraph::SetChannelMarkerFill(BOOL propVal)
{
	SetProperty(0x4c, VT_BOOL, propVal);
}

BOOL CComiGraph::GetLegendVisible()
{
	BOOL result;
	GetProperty(0x4d, VT_BOOL, (void*)&result);
	return result;
}

void CComiGraph::SetLegendVisible(BOOL propVal)
{
	SetProperty(0x4d, VT_BOOL, propVal);
}

short CComiGraph::GetLegendPosition()
{
	short result;
	GetProperty(0x4e, VT_I2, (void*)&result);
	return result;
}

void CComiGraph::SetLegendPosition(short propVal)
{
	SetProperty(0x4e, VT_I2, propVal);
}

long CComiGraph::GetLegendLineLength()
{
	long result;
	GetProperty(0x4f, VT_I4, (void*)&result);
	return result;
}

void CComiGraph::SetLegendLineLength(long propVal)
{
	SetProperty(0x4f, VT_I4, propVal);
}

long CComiGraph::GetLegendSpaceGap()
{
	long result;
	GetProperty(0x50, VT_I4, (void*)&result);
	return result;
}

void CComiGraph::SetLegendSpaceGap(long propVal)
{
	SetProperty(0x50, VT_I4, propVal);
}

unsigned long CComiGraph::GetLegendTextColor()
{
	unsigned long result;
	GetProperty(0x51, VT_I4, (void*)&result);
	return result;
}

void CComiGraph::SetLegendTextColor(unsigned long propVal)
{
	SetProperty(0x51, VT_I4, propVal);
}

BOOL CComiGraph::GetLegendFrameVisible()
{
	BOOL result;
	GetProperty(0x52, VT_BOOL, (void*)&result);
	return result;
}

void CComiGraph::SetLegendFrameVisible(BOOL propVal)
{
	SetProperty(0x52, VT_BOOL, propVal);
}

BOOL CComiGraph::GetLegendFillBackgnd()
{
	BOOL result;
	GetProperty(0x53, VT_BOOL, (void*)&result);
	return result;
}

void CComiGraph::SetLegendFillBackgnd(BOOL propVal)
{
	SetProperty(0x53, VT_BOOL, propVal);
}

unsigned long CComiGraph::GetLegendFrameColor()
{
	unsigned long result;
	GetProperty(0x54, VT_I4, (void*)&result);
	return result;
}

void CComiGraph::SetLegendFrameColor(unsigned long propVal)
{
	SetProperty(0x54, VT_I4, propVal);
}

unsigned long CComiGraph::GetLegendBackColor()
{
	unsigned long result;
	GetProperty(0x55, VT_I4, (void*)&result);
	return result;
}

void CComiGraph::SetLegendBackColor(unsigned long propVal)
{
	SetProperty(0x55, VT_I4, propVal);
}

long CComiGraph::GetLegendPosMarginL()
{
	long result;
	GetProperty(0x56, VT_I4, (void*)&result);
	return result;
}

void CComiGraph::SetLegendPosMarginL(long propVal)
{
	SetProperty(0x56, VT_I4, propVal);
}

long CComiGraph::GetLegendPosMarginR()
{
	long result;
	GetProperty(0x57, VT_I4, (void*)&result);
	return result;
}

void CComiGraph::SetLegendPosMarginR(long propVal)
{
	SetProperty(0x57, VT_I4, propVal);
}

long CComiGraph::GetLegendPosMarginT()
{
	long result;
	GetProperty(0x58, VT_I4, (void*)&result);
	return result;
}

void CComiGraph::SetLegendPosMarginT(long propVal)
{
	SetProperty(0x58, VT_I4, propVal);
}

long CComiGraph::GetLegendPosMarginB()
{
	long result;
	GetProperty(0x59, VT_I4, (void*)&result);
	return result;
}

void CComiGraph::SetLegendPosMarginB(long propVal)
{
	SetProperty(0x59, VT_I4, propVal);
}

BOOL CComiGraph::GetGradientEnable()
{
	BOOL result;
	GetProperty(0x5a, VT_BOOL, (void*)&result);
	return result;
}

void CComiGraph::SetGradientEnable(BOOL propVal)
{
	SetProperty(0x5a, VT_BOOL, propVal);
}

short CComiGraph::GetGradientBrightness()
{
	short result;
	GetProperty(0x5b, VT_I2, (void*)&result);
	return result;
}

void CComiGraph::SetGradientBrightness(short propVal)
{
	SetProperty(0x5b, VT_I2, propVal);
}

short CComiGraph::GetGradientStyle()
{
	short result;
	GetProperty(0x5c, VT_I2, (void*)&result);
	return result;
}

void CComiGraph::SetGradientStyle(short propVal)
{
	SetProperty(0x5c, VT_I2, propVal);
}

short CComiGraph::GetXAxisPrecision()
{
	short result;
	GetProperty(0x5d, VT_I2, (void*)&result);
	return result;
}

void CComiGraph::SetXAxisPrecision(short propVal)
{
	SetProperty(0x5d, VT_I2, propVal);
}

short CComiGraph::GetYAxisPrecision()
{
	short result;
	GetProperty(0x5e, VT_I2, (void*)&result);
	return result;
}

void CComiGraph::SetYAxisPrecision(short propVal)
{
	SetProperty(0x5e, VT_I2, propVal);
}

BOOL CComiGraph::GetZoomEnabled()
{
	BOOL result;
	GetProperty(0x5f, VT_BOOL, (void*)&result);
	return result;
}

void CComiGraph::SetZoomEnabled(BOOL propVal)
{
	SetProperty(0x5f, VT_BOOL, propVal);
}

unsigned long CComiGraph::GetSuppFrameColor()
{
	unsigned long result;
	GetProperty(0x60, VT_I4, (void*)&result);
	return result;
}

void CComiGraph::SetSuppFrameColor(unsigned long propVal)
{
	SetProperty(0x60, VT_I4, propVal);
}

short CComiGraph::GetSuppFrameID()
{
	short result;
	GetProperty(0x61, VT_I2, (void*)&result);
	return result;
}

void CComiGraph::SetSuppFrameID(short propVal)
{
	SetProperty(0x61, VT_I2, propVal);
}

long CComiGraph::GetFrameThick()
{
	long result;
	GetProperty(0x62, VT_I4, (void*)&result);
	return result;
}

void CComiGraph::SetFrameThick(long propVal)
{
	SetProperty(0x62, VT_I4, propVal);
}

long CComiGraph::GetMaxDataPoints()
{
	long result;
	GetProperty(0x63, VT_I4, (void*)&result);
	return result;
}

void CComiGraph::SetMaxDataPoints(long propVal)
{
	SetProperty(0x63, VT_I4, propVal);
}

short CComiGraph::GetScrollMode()
{
	short result;
	GetProperty(0x64, VT_I2, (void*)&result);
	return result;
}

void CComiGraph::SetScrollMode(short propVal)
{
	SetProperty(0x64, VT_I2, propVal);
}

float CComiGraph::GetBlockScrollBoundary()
{
	float result;
	GetProperty(0x65, VT_R4, (void*)&result);
	return result;
}

void CComiGraph::SetBlockScrollBoundary(float propVal)
{
	SetProperty(0x65, VT_R4, propVal);
}

BOOL CComiGraph::GetDragZoomEnabled()
{
	BOOL result;
	GetProperty(0x66, VT_BOOL, (void*)&result);
	return result;
}

void CComiGraph::SetDragZoomEnabled(BOOL propVal)
{
	SetProperty(0x66, VT_BOOL, propVal);
}

short CComiGraph::GetAxisCtrlMode()
{
	short result;
	GetProperty(0x67, VT_I2, (void*)&result);
	return result;
}

void CComiGraph::SetAxisCtrlMode(short propVal)
{
	SetProperty(0x67, VT_I2, propVal);
}

BOOL CComiGraph::GetCTBVisible()
{
	BOOL result;
	GetProperty(0x68, VT_BOOL, (void*)&result);
	return result;
}

void CComiGraph::SetCTBVisible(BOOL propVal)
{
	SetProperty(0x68, VT_BOOL, propVal);
}

short CComiGraph::GetCTBBorderStyle()
{
	short result;
	GetProperty(0x69, VT_I2, (void*)&result);
	return result;
}

void CComiGraph::SetCTBBorderStyle(short propVal)
{
	SetProperty(0x69, VT_I2, propVal);
}

BOOL CComiGraph::GetCTBFlatButton()
{
	BOOL result;
	GetProperty(0x6a, VT_BOOL, (void*)&result);
	return result;
}

void CComiGraph::SetCTBFlatButton(BOOL propVal)
{
	SetProperty(0x6a, VT_BOOL, propVal);
}

short CComiGraph::GetCTBButtonWidth()
{
	short result;
	GetProperty(0x6b, VT_I2, (void*)&result);
	return result;
}

void CComiGraph::SetCTBButtonWidth(short propVal)
{
	SetProperty(0x6b, VT_I2, propVal);
}

short CComiGraph::GetCTBButtonHeight()
{
	short result;
	GetProperty(0x6c, VT_I2, (void*)&result);
	return result;
}

void CComiGraph::SetCTBButtonHeight(short propVal)
{
	SetProperty(0x6c, VT_I2, propVal);
}

long CComiGraph::GetCTBItems()
{
	long result;
	GetProperty(0x6d, VT_I4, (void*)&result);
	return result;
}

void CComiGraph::SetCTBItems(long propVal)
{
	SetProperty(0x6d, VT_I4, propVal);
}

BOOL CComiGraph::GetXAxisAutoScale()
{
	BOOL result;
	GetProperty(0x6e, VT_BOOL, (void*)&result);
	return result;
}

void CComiGraph::SetXAxisAutoScale(BOOL propVal)
{
	SetProperty(0x6e, VT_BOOL, propVal);
}

BOOL CComiGraph::GetYAxisAutoScale()
{
	BOOL result;
	GetProperty(0x6f, VT_BOOL, (void*)&result);
	return result;
}

void CComiGraph::SetYAxisAutoScale(BOOL propVal)
{
	SetProperty(0x6f, VT_BOOL, propVal);
}

BOOL CComiGraph::GetDataStore()
{
	BOOL result;
	GetProperty(0x70, VT_BOOL, (void*)&result);
	return result;
}

void CComiGraph::SetDataStore(BOOL propVal)
{
	SetProperty(0x70, VT_BOOL, propVal);
}

long CComiGraph::GetPlotBufferSize()
{
	long result;
	GetProperty(0x71, VT_I4, (void*)&result);
	return result;
}

void CComiGraph::SetPlotBufferSize(long propVal)
{
	SetProperty(0x71, VT_I4, propVal);
}

short CComiGraph::GetPlotMode()
{
	short result;
	GetProperty(0x72, VT_I2, (void*)&result);
	return result;
}

void CComiGraph::SetPlotMode(short propVal)
{
	SetProperty(0x72, VT_I2, propVal);
}

/////////////////////////////////////////////////////////////////////////////
// CComiGraph operations

long CComiGraph::GetNumberOfXAxis()
{
	long result;
	InvokeHelper(0x73, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

long CComiGraph::AddXAxis()
{
	long result;
	InvokeHelper(0x74, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

void CComiGraph::DeleteXAxis(short nAxisIndex)
{
	static BYTE parms[] =
		VTS_I2;
	InvokeHelper(0x75, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 nAxisIndex);
}

long CComiGraph::GetNumberOfYAxis()
{
	long result;
	InvokeHelper(0x76, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

long CComiGraph::AddYAxis()
{
	long result;
	InvokeHelper(0x77, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

void CComiGraph::DeleteYAxis(short nAxisIndex)
{
	static BYTE parms[] =
		VTS_I2;
	InvokeHelper(0x78, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 nAxisIndex);
}

void CComiGraph::AddPlotChannel(short nXAxisIndex, short nYAxisIndex, unsigned long clColor)
{
	static BYTE parms[] =
		VTS_I2 VTS_I2 VTS_I4;
	InvokeHelper(0x79, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 nXAxisIndex, nYAxisIndex, clColor);
}

void CComiGraph::DeletePlotChannel(long nChannelIndex)
{
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x7a, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 nChannelIndex);
}

long CComiGraph::GetNumberOfChannels()
{
	long result;
	InvokeHelper(0x7b, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

long CComiGraph::GetCursorAttribute(short nCursorNo, short nAttributeID)
{
	long result;
	static BYTE parms[] =
		VTS_I2 VTS_I2;
	InvokeHelper(0x7c, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		nCursorNo, nAttributeID);
	return result;
}

void CComiGraph::SetCursorAttribute(short nCursorNo, short nAttributeID, long AttrValue)
{
	static BYTE parms[] =
		VTS_I2 VTS_I2 VTS_I4;
	InvokeHelper(0x7d, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 nCursorNo, nAttributeID, AttrValue);
}

void CComiGraph::PlotXY_VT(long nChannel, VARIANT* pXBuffer, short nXDataType, VARIANT* pYBuffer, short nYDataType, long nNumData)
{
	static BYTE parms[] =
		VTS_I4 VTS_PVARIANT VTS_I2 VTS_PVARIANT VTS_I2 VTS_I4;
	InvokeHelper(0x7e, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 nChannel, pXBuffer, nXDataType, pYBuffer, nYDataType, nNumData);
}

void CComiGraph::DeletePlot(long nChannel)
{
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x7f, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 nChannel);
}

long CComiGraph::XValueToPixel(short nXAxisIdx, double fXValue)
{
	long result;
	static BYTE parms[] =
		VTS_I2 VTS_R8;
	InvokeHelper(0x80, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		nXAxisIdx, fXValue);
	return result;
}

long CComiGraph::YValueToPixel(short nYAxisIdx, double fYValue)
{
	long result;
	static BYTE parms[] =
		VTS_I2 VTS_R8;
	InvokeHelper(0x81, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		nYAxisIdx, fYValue);
	return result;
}

void CComiGraph::RefreshAll()
{
	InvokeHelper(0x82, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void CComiGraph::SetXAxisRange(short nXAxisIdx, double fXMin, double fXMax, short bRedraw)
{
	static BYTE parms[] =
		VTS_I2 VTS_R8 VTS_R8 VTS_I2;
	InvokeHelper(0x83, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 nXAxisIdx, fXMin, fXMax, bRedraw);
}

void CComiGraph::SetYAxisRange(short nYAxisIdx, double fYMin, double fYMax, short bRedraw)
{
	static BYTE parms[] =
		VTS_I2 VTS_R8 VTS_R8 VTS_I2;
	InvokeHelper(0x84, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 nYAxisIdx, fYMin, fYMax, bRedraw);
}

void CComiGraph::PlotY_VT(long nChannel, VARIANT* pYBuffer, short nYDataType, double fXIniVal, double fXIncVal, long nNumData)
{
	static BYTE parms[] =
		VTS_I4 VTS_PVARIANT VTS_I2 VTS_R8 VTS_R8 VTS_I4;
	InvokeHelper(0x85, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 nChannel, pYBuffer, nYDataType, fXIniVal, fXIncVal, nNumData);
}

void CComiGraph::PlotX_VT(long nChannel, VARIANT* pXBuffer, short nXDataType, double fYIniVal, double fYIncVal, long nNumData)
{
	static BYTE parms[] =
		VTS_I4 VTS_PVARIANT VTS_I2 VTS_R8 VTS_R8 VTS_I4;
	InvokeHelper(0x86, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 nChannel, pXBuffer, nXDataType, fYIniVal, fYIncVal, nNumData);
}

void CComiGraph::GetCursorValue(short nCursorNo, double* pXVal, double* pYVal)
{
	static BYTE parms[] =
		VTS_I2 VTS_PR8 VTS_PR8;
	InvokeHelper(0x87, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 nCursorNo, pXVal, pYVal);
}

void CComiGraph::SetCursorValue(short nCursorNo, double fXVal, double fYVal)
{
	static BYTE parms[] =
		VTS_I2 VTS_R8 VTS_R8;
	InvokeHelper(0x88, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 nCursorNo, fXVal, fYVal);
}

double CComiGraph::GetCursorDeltaX()
{
	double result;
	InvokeHelper(0x89, DISPATCH_METHOD, VT_R8, (void*)&result, NULL);
	return result;
}

double CComiGraph::GetCursorDeltaY()
{
	double result;
	InvokeHelper(0x8a, DISPATCH_METHOD, VT_R8, (void*)&result, NULL);
	return result;
}

void CComiGraph::UpdatePlot()
{
	InvokeHelper(0x8b, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

long CComiGraph::SaveToTextFile(LPCTSTR szFilePath)
{
	long result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x8c, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		szFilePath);
	return result;
}

void CComiGraph::SaveToClipboard()
{
	InvokeHelper(0x8d, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void CComiGraph::PlotChart(long nChannel, double* pXBuf, double* pYBuf, long nNumData)
{
	static BYTE parms[] =
		VTS_I4 VTS_PR8 VTS_PR8 VTS_I4;
	InvokeHelper(0x8e, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 nChannel, pXBuf, pYBuf, nNumData);
}

void CComiGraph::SetChartPause(short bPause)
{
	static BYTE parms[] =
		VTS_I2;
	InvokeHelper(0x8f, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 bPause);
}

short CComiGraph::GetChartPause()
{
	short result;
	InvokeHelper(0x90, DISPATCH_METHOD, VT_I2, (void*)&result, NULL);
	return result;
}

void CComiGraph::PlotXY(long nChannel, double* pXBuffer, double* pYBuffer, long nNumData)
{
	static BYTE parms[] =
		VTS_I4 VTS_PR8 VTS_PR8 VTS_I4;
	InvokeHelper(0x91, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 nChannel, pXBuffer, pYBuffer, nNumData);
}

void CComiGraph::PlotX(long nChannel, double* pXBuffer, double fYIniVal, double fYIncVal, long nNumData)
{
	static BYTE parms[] =
		VTS_I4 VTS_PR8 VTS_R8 VTS_R8 VTS_I4;
	InvokeHelper(0x92, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 nChannel, pXBuffer, fYIniVal, fYIncVal, nNumData);
}

void CComiGraph::PlotY(long nChannel, double* pYBuffer, double fXIniVal, double fXIncVal, long nNumData)
{
	static BYTE parms[] =
		VTS_I4 VTS_PR8 VTS_R8 VTS_R8 VTS_I4;
	InvokeHelper(0x93, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 nChannel, pYBuffer, fXIniVal, fXIncVal, nNumData);
}

long CComiGraph::GetPlotDataX(long nChannel, double* pBuffer, long nCount)
{
	long result;
	static BYTE parms[] =
		VTS_I4 VTS_PR8 VTS_I4;
	InvokeHelper(0x94, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		nChannel, pBuffer, nCount);
	return result;
}

long CComiGraph::GetPlotDataY(long nChannel, double* pBuffer, long nCount)
{
	long result;
	static BYTE parms[] =
		VTS_I4 VTS_PR8 VTS_I4;
	InvokeHelper(0x95, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		nChannel, pBuffer, nCount);
	return result;
}

void CComiGraph::DisableScreenUpdate()
{
	InvokeHelper(0x96, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void CComiGraph::EnableScreenUpdate()
{
	InvokeHelper(0x97, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

short CComiGraph::Print(short bInvertColor)
{
	short result;
	static BYTE parms[] =
		VTS_I2;
	InvokeHelper(0x98, DISPATCH_METHOD, VT_I2, (void*)&result, parms,
		bInvertColor);
	return result;
}

void CComiGraph::PassKey(long nPassKey)
{
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x99, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 nPassKey);
}

long CComiGraph::GetPlotaDataNum(long nChannel)
{
	long result;
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x9a, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		nChannel);
	return result;
}

void CComiGraph::AboutBox()
{
	InvokeHelper(0xfffffdd8, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}
