#if !defined(AFX_TEXTURE_H__A33C0799_0E11_4478_9C21_1D41DC7EB7B6__INCLUDED_)
#define AFX_TEXTURE_H__A33C0799_0E11_4478_9C21_1D41DC7EB7B6__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CTexture wrapper class

class CTexture : public COleDispatchDriver
{
public:
	CTexture() {}		// Calls COleDispatchDriver default constructor
	CTexture(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CTexture(const CTexture& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:
	CString GetFilepath();
	void SetFilepath(LPCTSTR);
	long GetMode();
	void SetMode(long);
	short GetLightIntensity();
	void SetLightIntensity(short);
	unsigned long GetColorToMix();
	void SetColorToMix(unsigned long);
	short GetPercentageColorMix();
	void SetPercentageColorMix(short);

// Operations
public:
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_TEXTURE_H__A33C0799_0E11_4478_9C21_1D41DC7EB7B6__INCLUDED_)
